# Rename this file to languages.toml to enable multilingual support
[en]
    languageName      = "English"
    languagedirection = "ltr"
    title             = "White Margin"
    weight            = 1

# [zh-cn]
#     languageName      = "简体中文"
#     languagedirection = "ltr"
#     title             = "留白"
#     weight            = 2